inherit_gem:
  rubocop-github:
    - config/default.yml
plugins: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6

# Disable cops that are not consistently available across all Ruby versions
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false
